---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  namespace: prow
data:
  plugins.yaml: |
    plugins:
      3scale-ops:
      - approve
      - assign
      - blunderbuss
      - branchcleaner
      - mergecommitblocker
      - cat
      - dog
      - help
      - heart
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - owners-label
      - require-matching-label
      - retitle
      - shrug
      - size
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks
      3scale/3scale-saas:
      - approve
      - assign
      - blunderbuss
      - mergecommitblocker
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - owners-label
      - require-matching-label
      - retitle
      - size
      - trigger
      - verify-owners
      - wip
      3scale/platform:
      - approve
      - assign
      - blunderbuss
      - mergecommitblocker
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - owners-label
      - require-matching-label
      - retitle
      - size
      - trigger
      - verify-owners
      - wip

    require_matching_label:
      - missing_label: needs-kind
        org: 3scale-ops
        issues: true
        prs: true
        regexp: ^kind/
        missing_comment: |
          There are no kind on this issue.
          Please add an appropriate kind by using one of the following commands:
            - `/kind bug`
            - `/kind cleanup`
            - `/kind documentation`
            - `/kind feature`
            - `/kind <kind-name>`
      - missing_label: needs-priority
        org: 3scale-ops
        issues: true
        prs: true
        regexp: ^priority/
      - missing_label: needs-size
        org: 3scale-ops
        issues: true
        prs: true
        regexp: ^size/
      - missing_label: needs-kind
        org: 3scale
        issues: true
        prs: true
        regexp: ^kind/
        missing_comment: |
          There are no kind on this issue.
          Please add an appropriate kind by using one of the following commands:
            - `/kind bug`
            - `/kind cleanup`
            - `/kind documentation`
            - `/kind feature`
            - `/kind <kind-name>`
      - missing_label: needs-priority
        org: 3scale
        issues: true
        prs: true
        regexp: ^priority/
      - missing_label: needs-size
        org: 3scale
        issues: true
        prs: true
        regexp: ^size/
      - missing_label: needs-env
        org: 3scale
        issues: true
        prs: true
        regexp: ^env/

    label:
      additional_labels:
        - size/xs
        - size/s
        - size/m
        - size/l
        - size/xl
        - size/xxl
        - env/legacy
        - env/common
        - env/dev-eng
        - env/stg-saas
        - env/pro-base
        - env/pro-saas

    blunderbuss:
      # ExcludeApprovers controls whether approvers are considered to be
      # reviewers. By default, approvers are considered as reviewers if
      # insufficient reviewers are available. If ExcludeApprovers is true,
      # approvers will never be considered as reviewers.
      exclude_approvers: false

      # MaxReviewerCount is the maximum number of reviewers to request
      # reviews from. Defaults to 0 meaning no limit.
      max_request_count: 2

      # ReviewerCount is the minimum number of reviewers to request
      # reviews from. Defaults to requesting reviews from 2 reviewers
      request_count: 2

      # UseStatusAvailability controls whether blunderbuss will consider GitHub's
      # status availability when requesting reviews for users. This will use at one
      # additional token per successful reviewer (and potentially more depending on
      # how many busy reviewers it had to pass over).
      use_status_availability: true

    approve:
      - repos:
          - 3scale
          - 3scale-ops

        commandHelpLink: "https://prow.mgmt.3sca.net/command-help"

        # RequireSelfApproval requires PR authors to explicitly approve their PRs.
        # Otherwise the plugin assumes the author of the PR approves the changes in the PR.
        require_self_approval: true

        # IgnoreReviewState causes the approve plugin to ignore the GitHub review state. Otherwise:
        # * an APPROVE github review is equivalent to leaving an "/approve" message.
        # * A REQUEST_CHANGES github review is equivalent to leaving an /approve cancel" message.
        ignore_review_state: true

    lgtm:
      - repos:
          - 3scale
          - 3scale-ops

        # ReviewActsAsLgtm indicates that a GitHub review of "approve" or "request changes"
        # acts as adding or removing the lgtm label
        review_acts_as_lgtm: true

        # StoreTreeHash indicates if tree_hash should be stored inside a comment to detect
        # squashed commits before removing lgtm labels
        store_tree_hash: true

    size:
        s: 8
        m: 64
        l: 512
        xl: 2048
        xxl: 8192

    welcome:
      - repos:
          - 3scale-ops/tf-openshift-3.11
          - 3scale-ops/tf-vault-secret
          - 3scale-ops/aws-nlb-helper-operator
          - 3scale-ops/prometheus-exporter-operator
        message_template:  "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> ðŸŽ‰. Please refer to our <a href='https://github.com/{{.Org}}/{{.Repo}}#contributing'>contributing documentation</a> to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/main/CONTRIBUTING.md). <br><br>Thank you, and welcome to 3scale-ops. :smiley:"
      - repos:
          - 3scale-ops/marin3r
        message_template:  "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> ðŸŽ‰. Please refer to our <a href='https://github.com/{{.Org}}/{{.Repo}}/tree/main/docs/development'>contributing documentation</a> to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/main/CONTRIBUTING.md). <br><br>Thank you, and welcome to {{.Repo}}. :smiley:"
